// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseResource() {
  return window['go']['controller']['API']['CloseResource']();
}

export function GetAppConfig() {
  return window['go']['controller']['API']['GetAppConfig']();
}

export function GetBootConfig() {
  return window['go']['controller']['API']['GetBootConfig']();
}

export function GetSystemInfo() {
  return window['go']['controller']['API']['GetSystemInfo']();
}

export function GetUserData() {
  return window['go']['controller']['API']['GetUserData']();
}

export function SetAppConfig(arg1) {
  return window['go']['controller']['API']['SetAppConfig'](arg1);
}

export function SetBootConfig(arg1) {
  return window['go']['controller']['API']['SetBootConfig'](arg1);
}

export function SetUserData(arg1) {
  return window['go']['controller']['API']['SetUserData'](arg1);
}

export function TestLLM() {
  return window['go']['controller']['API']['TestLLM']();
}
