// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';

export function CloseResource():Promise<void>;

export function GetAppConfig():Promise<service.AppConfig>;

export function GetBootConfig():Promise<service.BootAppConfig>;

export function GetSystemInfo():Promise<service.SystemInfo>;

export function GetUserData():Promise<service.UData>;

export function SetAppConfig(arg1:service.AppConfig):Promise<void>;

export function SetBootConfig(arg1:string):Promise<void>;

export function SetUserData(arg1:service.UData):Promise<void>;

export function TestLLM():Promise<string>;
