// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {controller} from '../models';

export function GetAppConfig():Promise<controller.AppConfig>;

export function GetBootConfig():Promise<controller.BootAppConfig>;

export function GetSystemInfo():Promise<controller.SystemInfo>;

export function SetAppConfig(arg1:controller.AppConfig):Promise<void>;

export function SetBootConfig(arg1:string):Promise<void>;
