// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';

export function GetAppConfig():Promise<service.AppConfig>;

export function GetBootConfig():Promise<service.BootAppConfig>;

export function GetSystemInfo():Promise<service.SystemInfo>;

export function SetAppConfig(arg1:service.AppConfig):Promise<void>;

export function SetBootConfig(arg1:string):Promise<void>;
