// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppStatus() {
  return window['go']['controller']['DirController']['GetAppStatus']();
}

export function GetDiskInfo() {
  return window['go']['controller']['DirController']['GetDiskInfo']();
}

export function GetInitialDir(arg1) {
  return window['go']['controller']['DirController']['GetInitialDir'](arg1);
}

export function OpenDirectory(arg1) {
  return window['go']['controller']['DirController']['OpenDirectory'](arg1);
}
