// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDir(arg1, arg2) {
  return window['go']['controller']['DirController']['CreateDir'](arg1, arg2);
}

export function CreateFile(arg1, arg2) {
  return window['go']['controller']['DirController']['CreateFile'](arg1, arg2);
}

export function GetDiskInfo() {
  return window['go']['controller']['DirController']['GetDiskInfo']();
}

export function GetRetrieveDes() {
  return window['go']['controller']['DirController']['GetRetrieveDes']();
}

export function GetSearchInput(arg1, arg2) {
  return window['go']['controller']['DirController']['GetSearchInput'](arg1, arg2);
}

export function IndexDir(arg1) {
  return window['go']['controller']['DirController']['IndexDir'](arg1);
}

export function IndexFile(arg1) {
  return window['go']['controller']['DirController']['IndexFile'](arg1);
}

export function OpenDirectory(arg1) {
  return window['go']['controller']['DirController']['OpenDirectory'](arg1);
}
