// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateItem(arg1, arg2) {
  return window['go']['controller']['DirController']['CreateItem'](arg1, arg2);
}

export function DeleteItem(arg1) {
  return window['go']['controller']['DirController']['DeleteItem'](arg1);
}

export function GetDiskInfo() {
  return window['go']['controller']['DirController']['GetDiskInfo']();
}

export function GetRetrieveDes() {
  return window['go']['controller']['DirController']['GetRetrieveDes']();
}

export function IndexDir(arg1, arg2) {
  return window['go']['controller']['DirController']['IndexDir'](arg1, arg2);
}

export function IndexFile(arg1) {
  return window['go']['controller']['DirController']['IndexFile'](arg1);
}

export function OpenDirectory(arg1) {
  return window['go']['controller']['DirController']['OpenDirectory'](arg1);
}

export function RenameItem(arg1, arg2) {
  return window['go']['controller']['DirController']['RenameItem'](arg1, arg2);
}

export function SearchItemFromInput(arg1) {
  return window['go']['controller']['DirController']['SearchItemFromInput'](arg1);
}

export function SearchItemFromLLM(arg1) {
  return window['go']['controller']['DirController']['SearchItemFromLLM'](arg1);
}
