// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppStatus():Promise<Record<string, any>>;

export function GetInitialDir(arg1:string):Promise<void>;

export function OpenDirectory(arg1:string):Promise<string>;
