// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';

export function CreateDir(arg1:string,arg2:string):Promise<void>;

export function CreateFile(arg1:string,arg2:string):Promise<void>;

export function GetDiskInfo():Promise<Array<service.Disk>>;

export function GetRetrieveDes():Promise<string>;

export function GetSearchInput(arg1:string,arg2:string):Promise<Array<service.FileSystemEntry>>;

export function IndexDir(arg1:string):Promise<service.DirContent>;

export function IndexFile(arg1:string):Promise<service.FileSystemEntry>;

export function OpenDirectory(arg1:string):Promise<string>;
