// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {controller} from '../models';

export function GetAppStatus():Promise<Record<string, any>>;

export function GetDiskInfo():Promise<Array<controller.Disk>>;

export function GetInitialDir(arg1:string):Promise<void>;

export function OpenDirectory(arg1:string):Promise<string>;
